name: Deploy and Run Noplagiat Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            scp -r ${{ github.workspace }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:./no_plagiat_app/backend/
            cd ./no_plagiat_app/backend/backend-Noplagiat
            npm install
            pm2 restart no_plagiat_back || pm2 start app.js --name "no_plagiat_back"
            
            
            
            
            



